import Head from "next/head";
import Image from "next/image";
import styles from "../styles/About.module.css";

export default function About() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Hakkımızda</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <div className={styles.navBar}>
               <span className={styles.title}>
                  <Image
                     src="/korteks_logo.png"
                     alt="KORTEKS Logo"
                     width={50}
                     height={50}
                     style={{
                        cursor: "pointer",
                     }}
                     onClick={() => (window.location.href = "/")}
                  />
               </span>
               <div className={styles.navLinks}>
                  <a href="/">Ana Sayfa</a>
                  <a href="/about">Hakkımızda</a>
                  <a href="/contact">İletişim</a>
               </div>
            </div>
            <div className={styles.divider}></div>
            <div className={styles.sectionContainer}>
               <h2 className={styles.title}>Biz Kimiz?</h2>
               <p className={styles.description}>
                  Biz insan hayatını kolaylaştıracak projeler üzerine
                  çalışıyoruz. 3 kişiden oluşan bir ekibiz. Üçümüzün de okul
                  öncesinden gelen yazılıma ilgisi, lisede tanıştıktan sonra
                  kendimizi bu yönde geliştirmemize olanak sağladı. Türkiye'nin
                  en iyi liselerinden birinde olmamızın da etkisiyle, proje ve
                  mühendislik yarışmalarına katılma imkanı bulduk. Bunun
                  sonucunda robotik sistemleri ve yazılımı kullanarak otomasyon
                  projeleri üzerine çalışmaya başladık. Yapay zeka alanında
                  TÜBİTAK, Boğaziçi, İTÜ gibi kurumların yarışmalarında başarı
                  elde eden projeleremiz oldu. Bizce geleceği şekillendirmek,
                  böyle teknolojileri hayatımıza entgre etmekten geçiyor. Biz de
                  bunun için çalışıyoruz.
               </p>
            </div>
         </main>

         <footer className={styles.footer}>
            <div className={styles.korteks_logo_cnt}>
               <span className={styles.logo_korteks}>
                  <Image
                     src="/korteks_logo.png"
                     alt="KORTEKS Logo"
                     width={50}
                     height={50}
                  />
               </span>
            </div>
            <a
               href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
               target="_blank"
               rel="noopener noreferrer"
            >
               Powered by{" "}
               <span className={styles.logo_3fs}>
                  <Image
                     src="/3fs_logo.png"
                     alt="Vercel Logo"
                     width={52}
                     height={52}
                  />
               </span>
            </a>
         </footer>
      </div>
   );
}
