import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import styles from "../styles/About.module.css";

const texts = {
   description: {
      en: "We are working on projects that will make human life easier. We are a team of 3 people. The interest of all three of us in software from pre-school enabled us to develop ourselves in this direction after meeting in high school. With the effect of being one of the best high schools in Turkey, we had the opportunity to participate in project and engineering competitions. As a result, we started working on automation projects using robotic systems and software. In the field of artificial intelligence, we have had successful projects in competitions of institutions such as TÜBİTAK, Boğaziçi, and İTÜ. In our opinion, shaping the future depends on integrating such technologies into our lives. We are working for this too.",
      tr: "Biz insan hayatını kolaylaştıracak projeler üzerine çalışıyoruz. 3 kişiden oluşan bir ekibiz. Üçümüzün de okul öncesinden gelen yazılıma ilgisi, lisede tanıştıktan sonra kendimizi bu yönde geliştirmemize olanak sağladı. Türkiye'nin en iyi liselerinden birinde olmamızın da etkisiyle, proje ve mühendislik yarışmalarına katılma imkanı bulduk. Bunun sonucunda robotik sistemleri ve yazılımı kullanarak otomasyon projeleri üzerine çalışmaya başladık. Yapay zeka alanında TÜBİTAK, Boğaziçi, İTÜ gibi kurumların yarışmalarında başarı elde eden projeleremiz oldu. Bizce geleceği şekillendirmek, böyle teknolojileri hayatımıza entgre etmekten geçiyor. Biz de bunun için çalışıyoruz.",
      fr: "Nous travaillons sur des projets qui faciliteront la vie humaine. Nous sommes une équipe de 3 personnes. L'intérêt de nous trois pour les logiciels dès le préscolaire nous a permis de nous développer dans ce sens après une rencontre au lycée. Avec l'effet d'être l'un des meilleurs lycées de Turquie, nous avons eu l'opportunité de participer à des concours de projets et d'ingénierie. En conséquence, nous avons commencé à travailler sur des projets d'automatisation utilisant des systèmes robotiques et des logiciels. Dans le domaine de l'intelligence artificielle, nous avons eu des projets réussis dans des concours d'institutions telles que TÜBİTAK, Boğaziçi et İTÜ. À notre avis, façonner l'avenir dépend de l'intégration de ces technologies dans nos vies. Nous travaillons pour cela aussi.",
   },
   title: {
      en: "About Us",
      tr: "Biz Kimiz?",
      fr: "À propos de nous",
   },
};

export default function About() {
   const [locale, setLocale] = useState("en");
   useEffect(() => {
      setLocale(navigator.language.split(/[-_]/)[0]);
   }, []);
   return (
      <div className={styles.container}>
         <Head>
            <title>
               {locale === "en"
                  ? "About"
                  : locale === "tr"
                  ? "Hakkımızda"
                  : "À propos de nous"}
            </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main className={styles.main}>
            <div className={styles.navBar}>
               <span className={styles.title}>
                  <Image
                     src="/korteks_logo.png"
                     alt="KORTEKS Logo"
                     width={50}
                     height={50}
                     style={{
                        cursor: "pointer",
                     }}
                     onClick={() => (window.location.href = "/")}
                  />
               </span>
               <div className={styles.navLinks}>
                  <a href="/">
                     {locale === "en"
                        ? "Home"
                        : locale === "tr"
                        ? "Ana Sayfa"
                        : "Accueil"}
                  </a>
                  <a href={"/about"}>
                     {locale === "en"
                        ? "About"
                        : locale === "tr"
                        ? "Hakkımızda"
                        : "À propos"}
                  </a>
                  <a href={"/contact"}>
                     {locale === "en"
                        ? "Contact"
                        : locale === "tr"
                        ? "İletişim"
                        : "Contact"}
                  </a>
               </div>
            </div>
            <div className={styles.divider}></div>
            <div className={styles.sectionContainer}>
               <h2 className={styles.title}>
                  {locale === "en"
                     ? texts.title.en
                     : locale === "tr"
                     ? texts.title.tr
                     : texts.title.fr}
               </h2>
               <p className={styles.description}>
                  {locale === "en"
                     ? texts.description.en
                     : locale === "tr"
                     ? texts.description.tr
                     : texts.description.fr}
               </p>
            </div>
         </main>

         <footer className={styles.footer}>
            <div className={styles.korteks_logo_cnt}>
               <span className={styles.logo_korteks}>
                  <Image
                     src="/korteks_logo.png"
                     alt="KORTEKS Logo"
                     width={50}
                     height={50}
                  />
               </span>
            </div>
            <a
               href="https://github.com/3f-s"
               target="_blank"
               rel="noopener noreferrer"
            >
               Powered by{" "}
               <span className={styles.logo_3fs}>
                  <Image
                     src="/3fs_logo.png"
                     alt="Vercel Logo"
                     width={40}
                     height={40}
                  />
               </span>
            </a>
         </footer>
      </div>
   );
}
